version: '3.8'

services:
  oracle-xe-db1:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe-db1
    environment:
      - ORACLE_PWD=your_password
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - 1521:1521
    volumes:
      - oracle-db1-data:/opt/oracle/oradata
      - ./init-scripts:/docker-entrypoint-initdb.d

  oracle-xe-db2:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe-db2
    environment:
      - ORACLE_PWD=your_password
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - 1522:1521
    volumes:
      - oracle-db2-data:/opt/oracle/oradata
      - ./init-scripts:/docker-entrypoint-initdb.d

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
      - POSTGRES_USER=your_user
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  oracle-db1-data:
  oracle-db2-data:
  postgres-data:
